version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -b 0.0.0.0:8000 server.wsgi"
    container_name: national-park-explorer
    volumes:
      - .:/national-park-explorer
    ports:
      - "8000:8000"